import type { ImportMappingConfig } from '@/lib/import-mapping';

export const DRIVER_IMPORT_CONFIG: ImportMappingConfig = {
  systemFields: [
    'firstName',
    'lastName',
    'unitId',
    'email',
    'phoneNumber',
    'payType',
    'rate',
    'driverTariff',
    'insurance',
    'escrow',
    'eld',
    'adminFee',
    'fuel',
    'tolls',
    'terminationDate',
  ],
  requiredFields: ['firstName'],
  fieldLabels: {
    firstName: 'First Name or Name',
    lastName: 'Last Name',
    unitId: 'Unit ID',
    email: 'Email',
    phoneNumber: 'Contact number',
    payType: 'Pay Type (percentage/cpm)',
    rate: 'Rate',
    driverTariff: 'Driver Tariff (e.g. .60 cpm or 30% from gross)',
    insurance: 'Insurance (Weekly)',
    escrow: 'Escrow (Weekly)',
    eld: 'ELD',
    adminFee: 'Admin Fee',
    fuel: 'Fuel',
    tolls: 'Tolls',
    terminationDate: 'Termination Date',
  },
};

export const OWNER_IMPORT_CONFIG: ImportMappingConfig = {
  systemFields: [
    'name',
    'unitId',
    'percentage',
    'fuelRebate',
    'insurance',
    'escrow',
    'eld',
    'adminFee',
    'fuel',
    'tolls',
  ],
  requiredFields: ['name'],
  fieldLabels: {
    name: 'Name',
    unitId: 'Unit ID',
    percentage: 'Percentage (e.g. 0.88 or 88)',
    fuelRebate: 'Fuel Rebate (e.g. 0.5 for 50%)',
    insurance: 'Insurance (Weekly)',
    escrow: 'Escrow (Weekly)',
    eld: 'ELD',
    adminFee: 'Admin Fee',
    fuel: 'Fuel',
    tolls: 'Tolls',
  },
};

export const SETTLEMENTS_LOAD_IMPORT_CONFIG: ImportMappingConfig = {
  systemFields: [
    'loadNumber',
    'driverName',
    'pickupDate',
    'deliveryDate',
    'truckId',
    'trailerNumber',
    'pickupLocation',
    'deliveryLocation',
    'miles',
    'emptyMiles',
    'invoiceAmount',
    'reserveAmount',
    'primeRateSurcharge',
    'transactionFee',
    'factoringFee',
    'advance',
    'extraStops',
    'extraStopsPay',
    'brokerId',
    'invoiceId',
  ],
  requiredFields: ['loadNumber', 'driverName'],
  fieldLabels: {
    loadNumber: 'Load #',
    driverName: 'Driver Name',
    pickupDate: 'Pickup Date',
    deliveryDate: 'Delivery Date',
    truckId: 'Truck ID',
    trailerNumber: 'Trailer Number',
    pickupLocation: 'Pickup Location',
    deliveryLocation: 'Delivery Location',
    miles: 'Miles',
    emptyMiles: 'Empty Miles',
    invoiceAmount: 'Invoice Amount',
    reserveAmount: 'Reserve Amount',
    primeRateSurcharge: 'Prime Rate Surcharge',
    transactionFee: 'Transaction Fee',
    factoringFee: 'Factoring Fee',
    advance: 'Advance',
    extraStops: 'Extra Stops',
    extraStopsPay: 'Extra Stops Pay',
    brokerId: 'Broker ID',
    invoiceId: 'Invoice ID',
  },
};

export const SETTLEMENTS_EXPENSE_IMPORT_CONFIG: ImportMappingConfig = {
  systemFields: [
    'date',
    'description',
    'unitId',
    'amount',
    'gallons',
    'state',
    'billTo',
    'expenseType',
  ],
  requiredFields: ['description', 'amount'],
  fieldLabels: {
    date: 'Date',
    description: 'Description',
    unitId: 'Unit ID',
    amount: 'Amount',
    gallons: 'Gallons',
    state: 'State',
    billTo: 'Bill To (D/O/C)',
    expenseType: 'Expense Type',
  },
};

export const FACTORING_IMPORT_CONFIG: ImportMappingConfig = {
  systemFields: [
    'invoiceNumber',
    'loadNumber',
    'invoiceDate',
    'invoiceAmount',
    'advanceAmount',
    'transactionFee',
    'brokerName',
    'primeSurcharge',
    'wireFee',
  ],
  requiredFields: ['invoiceNumber'],
  fieldLabels: {
    invoiceNumber: 'Invoice Number',
    loadNumber: 'Load Number',
    invoiceDate: 'Invoice Date',
    invoiceAmount: 'Invoice Amount',
    advanceAmount: 'Advance Amount',
    transactionFee: 'Transaction Fee',
    brokerName: 'Broker Name',
    primeSurcharge: 'Prime Surcharge',
    wireFee: 'Wire Fee',
  },
};

export const BALANCE_SHEET_IMPORT_CONFIG: ImportMappingConfig = {
  systemFields: [
    // Assets
    "cash",
    "arUnfactored",
    "factoredReceivables",
    "factoredReserve",
    "fuelAdvances",
    "prepaid",
    "trucks",
    "trailers",
    "otherEquipment",
    "accumDep",
    "securityDeposits",
    "iftaCredits",
    // Liabilities
    "ap",
    "creditCards",
    "accrued",
    "payrollTaxes",
    "fuelCards",
    "factoringAdvance",
    "truckLoans",
    "otherLTDebt",
    // Equity
    "ownersCapital",
    "retainedEarnings",
  ],
  // Minimal required fields; retainedEarnings can be auto-balanced.
  requiredFields: ["cash", "ap", "ownersCapital"],
  fieldLabels: {
    // Assets
    cash: "Cash",
    arUnfactored: "Accounts Receivable (Unfactored)",
    factoredReceivables: "Factored Receivables",
    factoredReserve: "Factored Receivables (Reserve)",
    fuelAdvances: "Fuel Advances",
    prepaid: "Prepaid Expenses",
    trucks: "Trucks (cost)",
    trailers: "Trailers (cost)",
    otherEquipment: "Other Equipment (cost)",
    accumDep: "Accumulated Depreciation",
    securityDeposits: "Security Deposits",
    iftaCredits: "IFTA Credits / Refunds Receivable",
    // Liabilities
    ap: "Accounts Payable",
    creditCards: "Credit Cards",
    accrued: "Accrued Expenses",
    payrollTaxes: "Payroll & Payroll Taxes Payable",
    fuelCards: "Fuel Cards Payable",
    factoringAdvance: "Factoring Advance Liability",
    truckLoans: "Truck Loans / Leases Payable",
    otherLTDebt: "Other Long-Term Debt",
    // Equity
    ownersCapital: "Owner’s Capital / Paid-In Capital",
    retainedEarnings: "Retained Earnings",
  },
};
